### PR TITLE
Fix not supporting xcworkspace scheme correctly

### PR DESCRIPTION
**Pull request by lpusok**
### Checklist

- [x] I've read and accepted the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- Requires _PATCH_ [version update](https://semver.org/)

### Context

Fix for the case when the scheme is contained in the xcworkspace and not the project.
An example error this solves:
```
Failed to analyze project: failed to find the main target of the scheme (test): failed to find scheme (test) in project: scheme test not found in test.pbxproj
```

Update the logic modifying the Xcode project to preserve comments and order of keys. 
This adds better compatibility with Cordova (https://github.com/apache/cordova-node-xcode/) and agvtool.

### CODE REVIEW

**Review by godrei — COMMENTED** [review]
Pls, add a test case validating this change, other than that looks good to me.

**Review by godrei — DISMISSED** [review]

**Review by godrei — APPROVED** [review]

**Comment by jpike88** [comment]
@lpusok @godrei hi guys, just wondering if this has been release yet? How do I know in future when a publish to Bitrise has occurred?

**Comment by lpusok** [comment]
@jpike88 Sorry not released yet, found a blocking issue. Will be published when the new version is visible at https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/ios-auto-provision-appstoreconnect. Usually a few hours later when the new release is created in the current repo.
The new plan is to release the fix for using workspace schemes and the project modification part separately.

**Comment by jpike88** [comment]
Ok, I've been spending hours trying to get it to work, I'm seeing this error:

```
Analyzing project
Failed to analyze project: failed to find the main target of the scheme (Aquipa): failed to find scheme (Aquipa) in project: scheme Aquipa not found in Aquipa
```

My project is a Cordova one. I am assuming this will fix it...

**Comment by lpusok** [comment]
@jpike88 Supporting Cordova turned out to be complicated due to the fairly custom Xcode project parser included in Cordova. There is an additional fix still in the works, that hopefully will complete Cordova support.

**Comment by jpike88** [comment]
Can you link to that additional fix? I'm semi-manual with my workflow so it might not affect me, I may just only need this workspace scheme issue

**Comment by lpusok** [comment]
Do not have an public PR/issue for this yet. The issue is caused by the fact that this Step changes the signing settings in the project and ionic/cordova build fails to parse it. The scheme issue can be temporarily resolved if you move the scheme manually to be contained in the project rather then the workspace.

```CordovaError: Could not parse '[ ... ]/photo-gallery/platforms/ios/photo-gallery.xcodeproj/project.pbxproj: TypeError: Cannot read property 'buildSettings' of undefined
```

**Comment by jpike88** [comment]
I'll just hold out for the scheme fix is ok, I'm time poor right now.

PS: I had a workflow in GitHub actions previously, and used this plugin:

https://github.com/ngeri/prepare-signing

Then, I passed the ```--provisioningProfile``` flag to ```cordova build ios --release```, that seem to all work ok

**Comment by godrei** [comment]
@jpike88 these changes are released in version [1.0.2](https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/releases/tag/1.0.2), should be available in the StepLib in ~20m.

**Comment by jpike88** [comment]
Great I'll try it within the hour and let you know if it helped my issue

**Comment by jpike88** [comment]
Looks like it helped, thanks!

**Comment by jpike88** [comment]
Well, it got me a little further.

I'm now getting an error 65, likely to do with issue related to provisioning profile.

PS another note: in my GitHub Action, this line was useful:

My build.config (obfuscated): 

```{
    "ios": {
        "debug": {
            "developmentTeam": "***"
        },
        "release": {
            "developmentTeam": "***"
        }
    },
    "android": {
        "release": {
            "keystore": "android.keystore",
            "alias": "pg",
            "password": "***",
            "storePassword": "***",
            "keystoreType": ""
        }
    }
}```

And the command after using the signing step:

```$(npm bin)/cordova build ios --device --release --inc --buildConfig ./build.json --provisioningProfile=$(ls ~/Library/MobileDevice/Provisioning\ Profiles | grep mobile | sed 's/.mobileprovision//') --packageType=app-store```

**Comment by jpike88** [comment]
fyi looks like I'm at this stage now: https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/issues/34

Have moved there

**Pull request merged**
